//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Modelo_Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Modelo_Auditoria : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Modelo_AuditoriaEntities2 usando la cadena de conexión encontrada en la sección 'Modelo_AuditoriaEntities2' del archivo de configuración de la aplicación.
        /// </summary>
        public Modelo_Auditoria() : base("name=Modelo_AuditoriaEntities2", "Modelo_AuditoriaEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Modelo_AuditoriaEntities2.
        /// </summary>
        public Modelo_Auditoria(string connectionString) : base(connectionString, "Modelo_AuditoriaEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Modelo_AuditoriaEntities2.
        /// </summary>
        public Modelo_Auditoria(EntityConnection connection) : base(connection, "Modelo_AuditoriaEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Operacion_Auditoria> CatOperaciones_Auditoria
        {
            get
            {
                if ((_CatOperaciones_Auditoria == null))
                {
                    _CatOperaciones_Auditoria = base.CreateObjectSet<Operacion_Auditoria>("CatOperaciones_Auditoria");
                }
                return _CatOperaciones_Auditoria;
            }
        }
        private ObjectSet<Operacion_Auditoria> _CatOperaciones_Auditoria;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Log> Log_Historia
        {
            get
            {
                if ((_Log_Historia == null))
                {
                    _Log_Historia = base.CreateObjectSet<Log>("Log_Historia");
                }
                return _Log_Historia;
            }
        }
        private ObjectSet<Log> _Log_Historia;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CatOperaciones_Auditoria. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCatOperaciones_Auditoria(Operacion_Auditoria operacion_Auditoria)
        {
            base.AddObject("CatOperaciones_Auditoria", operacion_Auditoria);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Log_Historia. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLog_Historia(Log log)
        {
            base.AddObject("Log_Historia", log);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo_AuditoriaModel", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Log.
        /// </summary>
        /// <param name="nro_log">Valor inicial de la propiedad nro_log.</param>
        /// <param name="uSU_CODIGO">Valor inicial de la propiedad USU_CODIGO.</param>
        /// <param name="fecha_y_hora">Valor inicial de la propiedad fecha_y_hora.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        public static Log CreateLog(global::System.Int64 nro_log, global::System.String uSU_CODIGO, global::System.DateTime fecha_y_hora, global::System.String accion)
        {
            Log log = new Log();
            log.nro_log = nro_log;
            log.USU_CODIGO = uSU_CODIGO;
            log.fecha_y_hora = fecha_y_hora;
            log.accion = accion;
            return log;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nro_log
        {
            get
            {
                return _nro_log;
            }
            set
            {
                if (_nro_log != value)
                {
                    Onnro_logChanging(value);
                    ReportPropertyChanging("nro_log");
                    _nro_log = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nro_log");
                    Onnro_logChanged();
                }
            }
        }
        private global::System.Int64 _nro_log;
        partial void Onnro_logChanging(global::System.Int64 value);
        partial void Onnro_logChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CODIGO
        {
            get
            {
                return _USU_CODIGO;
            }
            set
            {
                if (_USU_CODIGO != value)
                {
                    OnUSU_CODIGOChanging(value);
                    ReportPropertyChanging("USU_CODIGO");
                    _USU_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USU_CODIGO");
                    OnUSU_CODIGOChanged();
                }
            }
        }
        private global::System.String _USU_CODIGO;
        partial void OnUSU_CODIGOChanging(global::System.String value);
        partial void OnUSU_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_y_hora
        {
            get
            {
                return _fecha_y_hora;
            }
            set
            {
                if (_fecha_y_hora != value)
                {
                    Onfecha_y_horaChanging(value);
                    ReportPropertyChanging("fecha_y_hora");
                    _fecha_y_hora = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha_y_hora");
                    Onfecha_y_horaChanged();
                }
            }
        }
        private global::System.DateTime _fecha_y_hora;
        partial void Onfecha_y_horaChanging(global::System.DateTime value);
        partial void Onfecha_y_horaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo_AuditoriaModel", Name="Operacion_Auditoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Operacion_Auditoria : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Operacion_Auditoria.
        /// </summary>
        /// <param name="nro_operacion">Valor inicial de la propiedad nro_operacion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="nro_chofer">Valor inicial de la propiedad nro_chofer.</param>
        /// <param name="nro_transporte">Valor inicial de la propiedad nro_transporte.</param>
        /// <param name="tipo_operacion">Valor inicial de la propiedad tipo_operacion.</param>
        /// <param name="uSU_CODIGO">Valor inicial de la propiedad USU_CODIGO.</param>
        /// <param name="fecha_y_hora_accion">Valor inicial de la propiedad fecha_y_hora_accion.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        /// <param name="nro_cliente">Valor inicial de la propiedad nro_cliente.</param>
        public static Operacion_Auditoria CreateOperacion_Auditoria(global::System.Int64 nro_operacion, global::System.Int32 estado, global::System.Int32 nro_chofer, global::System.Int32 nro_transporte, global::System.Int32 tipo_operacion, global::System.String uSU_CODIGO, global::System.DateTime fecha_y_hora_accion, global::System.String accion, global::System.Int32 nro_cliente)
        {
            Operacion_Auditoria operacion_Auditoria = new Operacion_Auditoria();
            operacion_Auditoria.nro_operacion = nro_operacion;
            operacion_Auditoria.estado = estado;
            operacion_Auditoria.nro_chofer = nro_chofer;
            operacion_Auditoria.nro_transporte = nro_transporte;
            operacion_Auditoria.tipo_operacion = tipo_operacion;
            operacion_Auditoria.USU_CODIGO = uSU_CODIGO;
            operacion_Auditoria.fecha_y_hora_accion = fecha_y_hora_accion;
            operacion_Auditoria.accion = accion;
            operacion_Auditoria.nro_cliente = nro_cliente;
            return operacion_Auditoria;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nro_operacion
        {
            get
            {
                return _nro_operacion;
            }
            set
            {
                if (_nro_operacion != value)
                {
                    Onnro_operacionChanging(value);
                    ReportPropertyChanging("nro_operacion");
                    _nro_operacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nro_operacion");
                    Onnro_operacionChanged();
                }
            }
        }
        private global::System.Int64 _nro_operacion;
        partial void Onnro_operacionChanging(global::System.Int64 value);
        partial void Onnro_operacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_y_hora_inicio
        {
            get
            {
                return _fecha_y_hora_inicio;
            }
            set
            {
                Onfecha_y_hora_inicioChanging(value);
                ReportPropertyChanging("fecha_y_hora_inicio");
                _fecha_y_hora_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_y_hora_inicio");
                Onfecha_y_hora_inicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_y_hora_inicio;
        partial void Onfecha_y_hora_inicioChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_y_hora_inicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_y_hora_fin
        {
            get
            {
                return _fecha_y_hora_fin;
            }
            set
            {
                Onfecha_y_hora_finChanging(value);
                ReportPropertyChanging("fecha_y_hora_fin");
                _fecha_y_hora_fin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_y_hora_fin");
                Onfecha_y_hora_finChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_y_hora_fin;
        partial void Onfecha_y_hora_finChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_y_hora_finChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notas
        {
            get
            {
                return _notas;
            }
            set
            {
                OnnotasChanging(value);
                ReportPropertyChanging("notas");
                _notas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notas");
                OnnotasChanged();
            }
        }
        private global::System.String _notas;
        partial void OnnotasChanging(global::System.String value);
        partial void OnnotasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> nro_documento
        {
            get
            {
                return _nro_documento;
            }
            set
            {
                Onnro_documentoChanging(value);
                ReportPropertyChanging("nro_documento");
                _nro_documento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nro_documento");
                Onnro_documentoChanged();
            }
        }
        private Nullable<global::System.Int64> _nro_documento;
        partial void Onnro_documentoChanging(Nullable<global::System.Int64> value);
        partial void Onnro_documentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nro_alquiler
        {
            get
            {
                return _nro_alquiler;
            }
            set
            {
                Onnro_alquilerChanging(value);
                ReportPropertyChanging("nro_alquiler");
                _nro_alquiler = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nro_alquiler");
                Onnro_alquilerChanged();
            }
        }
        private Nullable<global::System.Int32> _nro_alquiler;
        partial void Onnro_alquilerChanging(Nullable<global::System.Int32> value);
        partial void Onnro_alquilerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nro_chofer
        {
            get
            {
                return _nro_chofer;
            }
            set
            {
                Onnro_choferChanging(value);
                ReportPropertyChanging("nro_chofer");
                _nro_chofer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nro_chofer");
                Onnro_choferChanged();
            }
        }
        private global::System.Int32 _nro_chofer;
        partial void Onnro_choferChanging(global::System.Int32 value);
        partial void Onnro_choferChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nro_transporte
        {
            get
            {
                return _nro_transporte;
            }
            set
            {
                Onnro_transporteChanging(value);
                ReportPropertyChanging("nro_transporte");
                _nro_transporte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nro_transporte");
                Onnro_transporteChanged();
            }
        }
        private global::System.Int32 _nro_transporte;
        partial void Onnro_transporteChanging(global::System.Int32 value);
        partial void Onnro_transporteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> peso_inicial
        {
            get
            {
                return _peso_inicial;
            }
            set
            {
                Onpeso_inicialChanging(value);
                ReportPropertyChanging("peso_inicial");
                _peso_inicial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso_inicial");
                Onpeso_inicialChanged();
            }
        }
        private Nullable<global::System.Double> _peso_inicial;
        partial void Onpeso_inicialChanging(Nullable<global::System.Double> value);
        partial void Onpeso_inicialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> peso_final
        {
            get
            {
                return _peso_final;
            }
            set
            {
                Onpeso_finalChanging(value);
                ReportPropertyChanging("peso_final");
                _peso_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso_final");
                Onpeso_finalChanged();
            }
        }
        private Nullable<global::System.Double> _peso_final;
        partial void Onpeso_finalChanging(Nullable<global::System.Double> value);
        partial void Onpeso_finalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo_documento
        {
            get
            {
                return _tipo_documento;
            }
            set
            {
                Ontipo_documentoChanging(value);
                ReportPropertyChanging("tipo_documento");
                _tipo_documento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo_documento");
                Ontipo_documentoChanged();
            }
        }
        private global::System.String _tipo_documento;
        partial void Ontipo_documentoChanging(global::System.String value);
        partial void Ontipo_documentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipo_operacion
        {
            get
            {
                return _tipo_operacion;
            }
            set
            {
                Ontipo_operacionChanging(value);
                ReportPropertyChanging("tipo_operacion");
                _tipo_operacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo_operacion");
                Ontipo_operacionChanged();
            }
        }
        private global::System.Int32 _tipo_operacion;
        partial void Ontipo_operacionChanging(global::System.Int32 value);
        partial void Ontipo_operacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CODIGO
        {
            get
            {
                return _USU_CODIGO;
            }
            set
            {
                if (_USU_CODIGO != value)
                {
                    OnUSU_CODIGOChanging(value);
                    ReportPropertyChanging("USU_CODIGO");
                    _USU_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USU_CODIGO");
                    OnUSU_CODIGOChanged();
                }
            }
        }
        private global::System.String _USU_CODIGO;
        partial void OnUSU_CODIGOChanging(global::System.String value);
        partial void OnUSU_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_y_hora_accion
        {
            get
            {
                return _fecha_y_hora_accion;
            }
            set
            {
                if (_fecha_y_hora_accion != value)
                {
                    Onfecha_y_hora_accionChanging(value);
                    ReportPropertyChanging("fecha_y_hora_accion");
                    _fecha_y_hora_accion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha_y_hora_accion");
                    Onfecha_y_hora_accionChanged();
                }
            }
        }
        private global::System.DateTime _fecha_y_hora_accion;
        partial void Onfecha_y_hora_accionChanging(global::System.DateTime value);
        partial void Onfecha_y_hora_accionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nro_cliente
        {
            get
            {
                return _nro_cliente;
            }
            set
            {
                Onnro_clienteChanging(value);
                ReportPropertyChanging("nro_cliente");
                _nro_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nro_cliente");
                Onnro_clienteChanged();
            }
        }
        private global::System.Int32 _nro_cliente;
        partial void Onnro_clienteChanging(global::System.Int32 value);
        partial void Onnro_clienteChanged();

        #endregion

    
    }

    #endregion

    
}
