//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ModeloSeguridad", "FK_FORMULARIOS_MODULOS", "MODULOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Modelo_Entidades.MODULO), "FORMULARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.FORMULARIO), true)]
[assembly: EdmRelationshipAttribute("ModeloSeguridad", "FK_PERFILES_FORMULARIOS", "FORMULARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Modelo_Entidades.FORMULARIO), "PERFILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.PERFIL), true)]
[assembly: EdmRelationshipAttribute("ModeloSeguridad", "FK_PERFILES_GRUPOS", "GRUPOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Modelo_Entidades.GRUPO), "PERFILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.PERFIL), true)]
[assembly: EdmRelationshipAttribute("ModeloSeguridad", "FK_PERFILES_PERMISOS", "PERMISOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Modelo_Entidades.PERMISO), "PERFILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.PERFIL), true)]
[assembly: EdmRelationshipAttribute("ModeloSeguridad", "FORMULARIOS_PERMISOS", "FORMULARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.FORMULARIO), "PERMISOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.PERMISO))]
[assembly: EdmRelationshipAttribute("ModeloSeguridad", "USUARIOS_GRUPOS", "GRUPOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.GRUPO), "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo_Entidades.USUARIO))]

#endregion

namespace Modelo_Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloSeguridadContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloSeguridadContainer usando la cadena de conexión encontrada en la sección 'ModeloSeguridadContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloSeguridadContainer() : base("name=ModeloSeguridadContainer", "ModeloSeguridadContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloSeguridadContainer.
        /// </summary>
        public ModeloSeguridadContainer(string connectionString) : base(connectionString, "ModeloSeguridadContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloSeguridadContainer.
        /// </summary>
        public ModeloSeguridadContainer(EntityConnection connection) : base(connection, "ModeloSeguridadContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FORMULARIO> FORMULARIOS
        {
            get
            {
                if ((_FORMULARIOS == null))
                {
                    _FORMULARIOS = base.CreateObjectSet<FORMULARIO>("FORMULARIOS");
                }
                return _FORMULARIOS;
            }
        }
        private ObjectSet<FORMULARIO> _FORMULARIOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<GRUPO> GRUPOS
        {
            get
            {
                if ((_GRUPOS == null))
                {
                    _GRUPOS = base.CreateObjectSet<GRUPO>("GRUPOS");
                }
                return _GRUPOS;
            }
        }
        private ObjectSet<GRUPO> _GRUPOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MODULO> MODULOS
        {
            get
            {
                if ((_MODULOS == null))
                {
                    _MODULOS = base.CreateObjectSet<MODULO>("MODULOS");
                }
                return _MODULOS;
            }
        }
        private ObjectSet<MODULO> _MODULOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PERFIL> PERFILES
        {
            get
            {
                if ((_PERFILES == null))
                {
                    _PERFILES = base.CreateObjectSet<PERFIL>("PERFILES");
                }
                return _PERFILES;
            }
        }
        private ObjectSet<PERFIL> _PERFILES;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PERMISO> PERMISOS
        {
            get
            {
                if ((_PERMISOS == null))
                {
                    _PERMISOS = base.CreateObjectSet<PERMISO>("PERMISOS");
                }
                return _PERMISOS;
            }
        }
        private ObjectSet<PERMISO> _PERMISOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<USUARIO> USUARIOS
        {
            get
            {
                if ((_USUARIOS == null))
                {
                    _USUARIOS = base.CreateObjectSet<USUARIO>("USUARIOS");
                }
                return _USUARIOS;
            }
        }
        private ObjectSet<USUARIO> _USUARIOS;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FORMULARIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFORMULARIOS(FORMULARIO fORMULARIO)
        {
            base.AddObject("FORMULARIOS", fORMULARIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet GRUPOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGRUPOS(GRUPO gRUPO)
        {
            base.AddObject("GRUPOS", gRUPO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MODULOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMODULOS(MODULO mODULO)
        {
            base.AddObject("MODULOS", mODULO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PERFILES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPERFILES(PERFIL pERFIL)
        {
            base.AddObject("PERFILES", pERFIL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PERMISOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPERMISOS(PERMISO pERMISO)
        {
            base.AddObject("PERMISOS", pERMISO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet USUARIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUSUARIOS(USUARIO uSUARIO)
        {
            base.AddObject("USUARIOS", uSUARIO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="FORMULARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FORMULARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FORMULARIO.
        /// </summary>
        /// <param name="fRM_CODIGO">Valor inicial de la propiedad FRM_CODIGO.</param>
        public static FORMULARIO CreateFORMULARIO(global::System.String fRM_CODIGO)
        {
            FORMULARIO fORMULARIO = new FORMULARIO();
            fORMULARIO.FRM_CODIGO = fRM_CODIGO;
            return fORMULARIO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRM_CODIGO
        {
            get
            {
                return _FRM_CODIGO;
            }
            set
            {
                if (_FRM_CODIGO != value)
                {
                    OnFRM_CODIGOChanging(value);
                    ReportPropertyChanging("FRM_CODIGO");
                    _FRM_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FRM_CODIGO");
                    OnFRM_CODIGOChanged();
                }
            }
        }
        private global::System.String _FRM_CODIGO;
        partial void OnFRM_CODIGOChanging(global::System.String value);
        partial void OnFRM_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRM_DESCRIPCION
        {
            get
            {
                return _FRM_DESCRIPCION;
            }
            set
            {
                OnFRM_DESCRIPCIONChanging(value);
                ReportPropertyChanging("FRM_DESCRIPCION");
                _FRM_DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRM_DESCRIPCION");
                OnFRM_DESCRIPCIONChanged();
            }
        }
        private global::System.String _FRM_DESCRIPCION;
        partial void OnFRM_DESCRIPCIONChanging(global::System.String value);
        partial void OnFRM_DESCRIPCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRM_MODULO
        {
            get
            {
                return _FRM_MODULO;
            }
            set
            {
                OnFRM_MODULOChanging(value);
                ReportPropertyChanging("FRM_MODULO");
                _FRM_MODULO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRM_MODULO");
                OnFRM_MODULOChanged();
            }
        }
        private global::System.String _FRM_MODULO;
        partial void OnFRM_MODULOChanging(global::System.String value);
        partial void OnFRM_MODULOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRM_FORMULARIO
        {
            get
            {
                return _FRM_FORMULARIO;
            }
            set
            {
                OnFRM_FORMULARIOChanging(value);
                ReportPropertyChanging("FRM_FORMULARIO");
                _FRM_FORMULARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRM_FORMULARIO");
                OnFRM_FORMULARIOChanged();
            }
        }
        private global::System.String _FRM_FORMULARIO;
        partial void OnFRM_FORMULARIOChanging(global::System.String value);
        partial void OnFRM_FORMULARIOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_FORMULARIOS_MODULOS", "MODULOS")]
        public MODULO MODULOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "MODULOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "MODULOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MODULO> MODULOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "MODULOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MODULO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "MODULOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_FORMULARIOS", "PERFILES")]
        public EntityCollection<PERFIL> PERFILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "PERFILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "PERFILES", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FORMULARIOS_PERMISOS", "PERMISOS")]
        public EntityCollection<PERMISO> PERMISOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERMISO>("ModeloSeguridad.FORMULARIOS_PERMISOS", "PERMISOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERMISO>("ModeloSeguridad.FORMULARIOS_PERMISOS", "PERMISOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="GRUPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GRUPO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto GRUPO.
        /// </summary>
        /// <param name="gRU_CODIGO">Valor inicial de la propiedad GRU_CODIGO.</param>
        public static GRUPO CreateGRUPO(global::System.String gRU_CODIGO)
        {
            GRUPO gRUPO = new GRUPO();
            gRUPO.GRU_CODIGO = gRU_CODIGO;
            return gRUPO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GRU_CODIGO
        {
            get
            {
                return _GRU_CODIGO;
            }
            set
            {
                if (_GRU_CODIGO != value)
                {
                    OnGRU_CODIGOChanging(value);
                    ReportPropertyChanging("GRU_CODIGO");
                    _GRU_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GRU_CODIGO");
                    OnGRU_CODIGOChanged();
                }
            }
        }
        private global::System.String _GRU_CODIGO;
        partial void OnGRU_CODIGOChanging(global::System.String value);
        partial void OnGRU_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GRU_DESCRIPCION
        {
            get
            {
                return _GRU_DESCRIPCION;
            }
            set
            {
                OnGRU_DESCRIPCIONChanging(value);
                ReportPropertyChanging("GRU_DESCRIPCION");
                _GRU_DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GRU_DESCRIPCION");
                OnGRU_DESCRIPCIONChanged();
            }
        }
        private global::System.String _GRU_DESCRIPCION;
        partial void OnGRU_DESCRIPCIONChanging(global::System.String value);
        partial void OnGRU_DESCRIPCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GRU_ESTADO
        {
            get
            {
                return _GRU_ESTADO;
            }
            set
            {
                OnGRU_ESTADOChanging(value);
                ReportPropertyChanging("GRU_ESTADO");
                _GRU_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GRU_ESTADO");
                OnGRU_ESTADOChanged();
            }
        }
        private Nullable<global::System.Boolean> _GRU_ESTADO;
        partial void OnGRU_ESTADOChanging(Nullable<global::System.Boolean> value);
        partial void OnGRU_ESTADOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_GRUPOS", "PERFILES")]
        public EntityCollection<PERFIL> PERFILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_GRUPOS", "PERFILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_GRUPOS", "PERFILES", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "USUARIOS_GRUPOS", "USUARIOS")]
        public EntityCollection<USUARIO> USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIO>("ModeloSeguridad.USUARIOS_GRUPOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIO>("ModeloSeguridad.USUARIOS_GRUPOS", "USUARIOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="MODULO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MODULO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MODULO.
        /// </summary>
        /// <param name="mOD_CODIGO">Valor inicial de la propiedad MOD_CODIGO.</param>
        public static MODULO CreateMODULO(global::System.String mOD_CODIGO)
        {
            MODULO mODULO = new MODULO();
            mODULO.MOD_CODIGO = mOD_CODIGO;
            return mODULO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MOD_CODIGO
        {
            get
            {
                return _MOD_CODIGO;
            }
            set
            {
                if (_MOD_CODIGO != value)
                {
                    OnMOD_CODIGOChanging(value);
                    ReportPropertyChanging("MOD_CODIGO");
                    _MOD_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MOD_CODIGO");
                    OnMOD_CODIGOChanged();
                }
            }
        }
        private global::System.String _MOD_CODIGO;
        partial void OnMOD_CODIGOChanging(global::System.String value);
        partial void OnMOD_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOD_DESCRIPCION
        {
            get
            {
                return _MOD_DESCRIPCION;
            }
            set
            {
                OnMOD_DESCRIPCIONChanging(value);
                ReportPropertyChanging("MOD_DESCRIPCION");
                _MOD_DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MOD_DESCRIPCION");
                OnMOD_DESCRIPCIONChanged();
            }
        }
        private global::System.String _MOD_DESCRIPCION;
        partial void OnMOD_DESCRIPCIONChanging(global::System.String value);
        partial void OnMOD_DESCRIPCIONChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_FORMULARIOS_MODULOS", "FORMULARIOS")]
        public EntityCollection<FORMULARIO> FORMULARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FORMULARIO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "FORMULARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FORMULARIO>("ModeloSeguridad.FK_FORMULARIOS_MODULOS", "FORMULARIOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="PERFIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PERFIL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PERFIL.
        /// </summary>
        /// <param name="pRF_CODIGO">Valor inicial de la propiedad PRF_CODIGO.</param>
        public static PERFIL CreatePERFIL(global::System.Int32 pRF_CODIGO)
        {
            PERFIL pERFIL = new PERFIL();
            pERFIL.PRF_CODIGO = pRF_CODIGO;
            return pERFIL;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRF_CODIGO
        {
            get
            {
                return _PRF_CODIGO;
            }
            set
            {
                if (_PRF_CODIGO != value)
                {
                    OnPRF_CODIGOChanging(value);
                    ReportPropertyChanging("PRF_CODIGO");
                    _PRF_CODIGO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PRF_CODIGO");
                    OnPRF_CODIGOChanged();
                }
            }
        }
        private global::System.Int32 _PRF_CODIGO;
        partial void OnPRF_CODIGOChanging(global::System.Int32 value);
        partial void OnPRF_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRM_CODIGO
        {
            get
            {
                return _FRM_CODIGO;
            }
            set
            {
                OnFRM_CODIGOChanging(value);
                ReportPropertyChanging("FRM_CODIGO");
                _FRM_CODIGO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRM_CODIGO");
                OnFRM_CODIGOChanged();
            }
        }
        private global::System.String _FRM_CODIGO;
        partial void OnFRM_CODIGOChanging(global::System.String value);
        partial void OnFRM_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GRU_CODIGO
        {
            get
            {
                return _GRU_CODIGO;
            }
            set
            {
                OnGRU_CODIGOChanging(value);
                ReportPropertyChanging("GRU_CODIGO");
                _GRU_CODIGO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GRU_CODIGO");
                OnGRU_CODIGOChanged();
            }
        }
        private global::System.String _GRU_CODIGO;
        partial void OnGRU_CODIGOChanging(global::System.String value);
        partial void OnGRU_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PER_CODIGO
        {
            get
            {
                return _PER_CODIGO;
            }
            set
            {
                OnPER_CODIGOChanging(value);
                ReportPropertyChanging("PER_CODIGO");
                _PER_CODIGO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PER_CODIGO");
                OnPER_CODIGOChanged();
            }
        }
        private global::System.String _PER_CODIGO;
        partial void OnPER_CODIGOChanging(global::System.String value);
        partial void OnPER_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AU_USUARIO
        {
            get
            {
                return _AU_USUARIO;
            }
            set
            {
                OnAU_USUARIOChanging(value);
                ReportPropertyChanging("AU_USUARIO");
                _AU_USUARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AU_USUARIO");
                OnAU_USUARIOChanged();
            }
        }
        private global::System.String _AU_USUARIO;
        partial void OnAU_USUARIOChanging(global::System.String value);
        partial void OnAU_USUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AU_FECHA
        {
            get
            {
                return _AU_FECHA;
            }
            set
            {
                OnAU_FECHAChanging(value);
                ReportPropertyChanging("AU_FECHA");
                _AU_FECHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AU_FECHA");
                OnAU_FECHAChanged();
            }
        }
        private Nullable<global::System.DateTime> _AU_FECHA;
        partial void OnAU_FECHAChanging(Nullable<global::System.DateTime> value);
        partial void OnAU_FECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AU_MOVIMIENTO
        {
            get
            {
                return _AU_MOVIMIENTO;
            }
            set
            {
                OnAU_MOVIMIENTOChanging(value);
                ReportPropertyChanging("AU_MOVIMIENTO");
                _AU_MOVIMIENTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AU_MOVIMIENTO");
                OnAU_MOVIMIENTOChanged();
            }
        }
        private global::System.String _AU_MOVIMIENTO;
        partial void OnAU_MOVIMIENTOChanging(global::System.String value);
        partial void OnAU_MOVIMIENTOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_FORMULARIOS", "FORMULARIOS")]
        public FORMULARIO FORMULARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORMULARIO>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "FORMULARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORMULARIO>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "FORMULARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FORMULARIO> FORMULARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORMULARIO>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "FORMULARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FORMULARIO>("ModeloSeguridad.FK_PERFILES_FORMULARIOS", "FORMULARIOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_GRUPOS", "GRUPOS")]
        public GRUPO GRUPOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("ModeloSeguridad.FK_PERFILES_GRUPOS", "GRUPOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("ModeloSeguridad.FK_PERFILES_GRUPOS", "GRUPOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GRUPO> GRUPOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("ModeloSeguridad.FK_PERFILES_GRUPOS", "GRUPOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GRUPO>("ModeloSeguridad.FK_PERFILES_GRUPOS", "GRUPOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_PERMISOS", "PERMISOS")]
        public PERMISO PERMISOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PERMISO>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERMISOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PERMISO>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERMISOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PERMISO> PERMISOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PERMISO>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERMISOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PERMISO>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERMISOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="PERMISO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PERMISO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PERMISO.
        /// </summary>
        /// <param name="pER_CODIGO">Valor inicial de la propiedad PER_CODIGO.</param>
        public static PERMISO CreatePERMISO(global::System.String pER_CODIGO)
        {
            PERMISO pERMISO = new PERMISO();
            pERMISO.PER_CODIGO = pER_CODIGO;
            return pERMISO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_CODIGO
        {
            get
            {
                return _PER_CODIGO;
            }
            set
            {
                if (_PER_CODIGO != value)
                {
                    OnPER_CODIGOChanging(value);
                    ReportPropertyChanging("PER_CODIGO");
                    _PER_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PER_CODIGO");
                    OnPER_CODIGOChanged();
                }
            }
        }
        private global::System.String _PER_CODIGO;
        partial void OnPER_CODIGOChanging(global::System.String value);
        partial void OnPER_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PER_DESCRIPCION
        {
            get
            {
                return _PER_DESCRIPCION;
            }
            set
            {
                OnPER_DESCRIPCIONChanging(value);
                ReportPropertyChanging("PER_DESCRIPCION");
                _PER_DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PER_DESCRIPCION");
                OnPER_DESCRIPCIONChanged();
            }
        }
        private global::System.String _PER_DESCRIPCION;
        partial void OnPER_DESCRIPCIONChanging(global::System.String value);
        partial void OnPER_DESCRIPCIONChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FK_PERFILES_PERMISOS", "PERFILES")]
        public EntityCollection<PERFIL> PERFILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERFILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERFIL>("ModeloSeguridad.FK_PERFILES_PERMISOS", "PERFILES", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "FORMULARIOS_PERMISOS", "FORMULARIOS")]
        public EntityCollection<FORMULARIO> FORMULARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FORMULARIO>("ModeloSeguridad.FORMULARIOS_PERMISOS", "FORMULARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FORMULARIO>("ModeloSeguridad.FORMULARIOS_PERMISOS", "FORMULARIOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloSeguridad", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto USUARIO.
        /// </summary>
        /// <param name="uSU_CODIGO">Valor inicial de la propiedad USU_CODIGO.</param>
        /// <param name="uSU_APELLIDO">Valor inicial de la propiedad USU_APELLIDO.</param>
        /// <param name="uSU_EMAIL">Valor inicial de la propiedad USU_EMAIL.</param>
        public static USUARIO CreateUSUARIO(global::System.String uSU_CODIGO, global::System.String uSU_APELLIDO, global::System.String uSU_EMAIL)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.USU_CODIGO = uSU_CODIGO;
            uSUARIO.USU_APELLIDO = uSU_APELLIDO;
            uSUARIO.USU_EMAIL = uSU_EMAIL;
            return uSUARIO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CODIGO
        {
            get
            {
                return _USU_CODIGO;
            }
            set
            {
                if (_USU_CODIGO != value)
                {
                    OnUSU_CODIGOChanging(value);
                    ReportPropertyChanging("USU_CODIGO");
                    _USU_CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USU_CODIGO");
                    OnUSU_CODIGOChanged();
                }
            }
        }
        private global::System.String _USU_CODIGO;
        partial void OnUSU_CODIGOChanging(global::System.String value);
        partial void OnUSU_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USU_NOMBRE
        {
            get
            {
                return _USU_NOMBRE;
            }
            set
            {
                OnUSU_NOMBREChanging(value);
                ReportPropertyChanging("USU_NOMBRE");
                _USU_NOMBRE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USU_NOMBRE");
                OnUSU_NOMBREChanged();
            }
        }
        private global::System.String _USU_NOMBRE;
        partial void OnUSU_NOMBREChanging(global::System.String value);
        partial void OnUSU_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> USU_ESTADO
        {
            get
            {
                return _USU_ESTADO;
            }
            set
            {
                OnUSU_ESTADOChanging(value);
                ReportPropertyChanging("USU_ESTADO");
                _USU_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USU_ESTADO");
                OnUSU_ESTADOChanged();
            }
        }
        private Nullable<global::System.Boolean> _USU_ESTADO;
        partial void OnUSU_ESTADOChanging(Nullable<global::System.Boolean> value);
        partial void OnUSU_ESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USU_CLAVE
        {
            get
            {
                return _USU_CLAVE;
            }
            set
            {
                OnUSU_CLAVEChanging(value);
                ReportPropertyChanging("USU_CLAVE");
                _USU_CLAVE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USU_CLAVE");
                OnUSU_CLAVEChanged();
            }
        }
        private global::System.String _USU_CLAVE;
        partial void OnUSU_CLAVEChanging(global::System.String value);
        partial void OnUSU_CLAVEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_APELLIDO
        {
            get
            {
                return _USU_APELLIDO;
            }
            set
            {
                OnUSU_APELLIDOChanging(value);
                ReportPropertyChanging("USU_APELLIDO");
                _USU_APELLIDO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_APELLIDO");
                OnUSU_APELLIDOChanged();
            }
        }
        private global::System.String _USU_APELLIDO;
        partial void OnUSU_APELLIDOChanging(global::System.String value);
        partial void OnUSU_APELLIDOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_EMAIL
        {
            get
            {
                return _USU_EMAIL;
            }
            set
            {
                OnUSU_EMAILChanging(value);
                ReportPropertyChanging("USU_EMAIL");
                _USU_EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_EMAIL");
                OnUSU_EMAILChanged();
            }
        }
        private global::System.String _USU_EMAIL;
        partial void OnUSU_EMAILChanging(global::System.String value);
        partial void OnUSU_EMAILChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloSeguridad", "USUARIOS_GRUPOS", "GRUPOS")]
        public EntityCollection<GRUPO> GRUPOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GRUPO>("ModeloSeguridad.USUARIOS_GRUPOS", "GRUPOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GRUPO>("ModeloSeguridad.USUARIOS_GRUPOS", "GRUPOS", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
